version: "3.8"

services:
  database:
    image: chriseaton/adventureworks:latest
    container_name: adventureworks
    restart: unless-stopped
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD:?}
